import { GalleryItem } from "@/type";

export const galleryItems: GalleryItem[] = [
    {
        id: "1",
        title: "American Cancer Society",
        category: "event",
        gallery: [
            "american_cancer_society/1.jpg",
            "american_cancer_society/2.jpg",
            "american_cancer_society/3.jpg",
            "american_cancer_society/4.jpg",
            "american_cancer_society/5.jpg",
            "american_cancer_society/6.jpg",
            "american_cancer_society/7.jpg",
            "american_cancer_society/8.jpg",
            "american_cancer_society/10.jpg",
            "american_cancer_society/11.jpg",
            "american_cancer_society/12.jpg",
            "american_cancer_society/13.jpg",
            "american_cancer_society/14.jpg",
            "american_cancer_society/15.jpg",
            "american_cancer_society/16.jpg",
            "american_cancer_society/17.jpg",
            "american_cancer_society/18.jpg",
            "american_cancer_society/19.jpg",
            "american_cancer_society/20.jpg",
            "american_cancer_society/21.jpg",
            "american_cancer_society/22.jpg",
            "american_cancer_society/23.jpg",
            "american_cancer_society/24.jpg",
            "american_cancer_society/25.jpg",
            "american_cancer_society/26.jpg",
            "american_cancer_society/27.jpg",
            "american_cancer_society/28.jpg",
            "american_cancer_society/29.jpg",
            "american_cancer_society/30.jpg",
            "american_cancer_society/31.jpg",
        ],
        slug: "american-cancer-society",
    },
    {
        id: "2",
        title: "Cape Fusion",
        category: "tour",
        gallery: [
            "cape_fusion/1.jpg",
            "cape_fusion/2.jpg",
            "cape_fusion/3.jpg",
            "cape_fusion/4.jpg",
            "cape_fusion/5.jpg",
            "cape_fusion/6.jpg",
            "cape_fusion/7.jpg",
            "cape_fusion/8.jpg",
            "cape_fusion/9.jpg",
            "cape_fusion/10.jpg",
            "cape_fusion/11.jpg",
        ],
        slug: "cape-fusion",
    },
    {
        id: "3",
        title: "Zember Ghana",
        category: "tour",
        gallery: [
            "zember_ghana/1.jpg",
            "zember_ghana/2.jpg",
            "zember_ghana/3.jpg",
            "zember_ghana/4.jpg",
            "zember_ghana/5.jpg",
            "zember_ghana/6.jpg",
            "zember_ghana/7.jpg",
            "zember_ghana/8.jpg",
            "zember_ghana/9.jpg",
            "zember_ghana/10.jpg",
            "zember_ghana/11.jpg",
            "zember_ghana/12.jpg",
            "zember_ghana/13.jpg",
            "zember_ghana/14.jpg",
            "zember_ghana/15.jpg",
            "zember_ghana/16.jpg",
            "zember_ghana/17.jpg",
            "zember_ghana/18.jpg",
            "zember_ghana/19.jpg",
            "zember_ghana/20.jpg",
            "zember_ghana/21.jpg",
            "zember_ghana/22.jpg",
            "zember_ghana/23.jpg",
            "zember_ghana/24.jpg",
            "zember_ghana/25.jpg",
            "zember_ghana/26.jpg",
            "zember_ghana/27.jpg",
            "zember_ghana/28.jpg",
            "zember_ghana/29.jpg",
            "zember_ghana/30.jpg",
        ],
        slug: "zember-ghana",
    },
    {
        id: "4",
        title: "Royal Ade Festival",
        category: "tour",
        gallery: [
            "royal_ade_festival/1.jpg",
            "royal_ade_festival/2.jpg",
            "royal_ade_festival/3.jpg",
            "royal_ade_festival/4.jpg",
            "royal_ade_festival/5.jpg",
            "royal_ade_festival/6.jpg",
            "royal_ade_festival/7.jpg",
            "royal_ade_festival/8.jpg",
            "royal_ade_festival/9.jpg",
            "royal_ade_festival/10.jpg",
            "royal_ade_festival/11.jpg",
            "royal_ade_festival/12.jpg",
            "royal_ade_festival/13.jpg",
            "royal_ade_festival/14.jpg",
            "royal_ade_festival/15.jpg",
        ],
        slug: "royal-ade-festival",
    },
    {
        id: "5",
        title: "GHVibes - Initiation",
        category: "tour",
        gallery: [
            "ghvibe_initiation/1.jpg",
            "ghvibe_initiation/2.jpg",
            "ghvibe_initiation/3.jpg"
        ],
        slug: "ghvibes-initiation",
    },
]
